server:
  port: 2222

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testspringboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

  kafka:
    bootstrap-servers: 192.168.0.47:9092 #指定kafka server的地址，集群配多个，中间，逗号隔开
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default_consumer_group_zpt #群组ID
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false

  rabbitmq:
    host: localhost
    port: 5672
    username: zpt
    password: zpt0305

  jpa:
    database: mysql
    showSql: true

  devtools:
      livereload:
        port: 35730

  main:
    allow-bean-definition-overriding: true

  redis:
    database: 1
    host: 127.0.0.1
    port: 6399

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  resources:
    static-locations: classpath:static/

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zpt.demo.model

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
    global-config:
      db-config:
        table-prefix:
        id-type: auto
      # cache-enabled: true
      # mapUnderscoreToCamelCase: true


